### ISSUE TITLE
Once installed, PersistentIdentifiers affects API display in browser

### ISSUE THREAD

**Issue by mephillips-durham** [omeka-s-modules/PersistentIdentifiers#10]
I installed PersistentIdentifiers 1.1.1 but did not configure either EZID or DataCite. I noticed that after installing, if I view an item through the API in my web browser (Microsoft Edge) then instead of displaying JSON-LD in the browser I am given an HTML version. For example, going to https://myserver/omeka-s/api/items/2822 it redirects to https://myserver/omeka-s/item/2822 and displays the item in HTML rather than JSON-LD.

![image](https://github.com/user-attachments/assets/612160cf-da57-4011-ad1a-ea5f001aa1f0)

Uninstall the module again, and the redirection no longer occurs and I can view the JSON-LD.

**Comment by matthewjmckinley** [comment]
This behavior is actually a current 'feature' of the module--since an Omeka item's URL will change depending on which site it is published on, or have none for items that are not published at all, we needed an unchanging, site-agnostic URL to point to as the _target for a persistent identifier link. The only URL that fit the bill is the item's Omeka API link, but then we also needed to show the end user something more user-friendly/human readable, so this module performs some content negotiation and header-checking to redirect item API calls issuing from a browser to a 'generic' item landing page unconnected to any particular site.

Note that by 'from a browser', I mean we're checking to see if the request sends an 'Accept: text/html' header--so item API calls from the command line/cURL, other APIs etc. should not be affected. It's not an ideal scenario, but given that the resolving process of persistent identifier linkage is more complicated than say a straightforward URL hyperlink, it can get pretty tricky identifying a stable way to read and negotiate by the link's source, which would be the presumed method for fine-tuning the redirect to only work on ARK and DOI urls.

That said, if you have a specific production use case for needing to access Omeka item API URLs via browser, while still utilizing the Persistent Identifier module, that this behavior breaks, I'd be happy to revisit this functionality and see if I can indeed fine tune it more!

**Comment by mephillips-durham** [comment]
Thanks - that makes sense. At first I was wondering why you could not make https://myserver/omeka-s/item/2822 the target of the persistent identifier link, and redirect to the API URL if it isn't a browser, but I suppose it's more sensible this way round.

This has been useful, however, to alert me to the fact that the persistent identifier will not link to the item in the context of a particular site. For one of the use cases we are investigating - a research data repository - we would definitely prefer the DOI to resolve to a page within the preferred site. I expect that is achievable if we modify the code somehow.
